language: node_js
node_js:
  - "8"

cache: npm

branches:
  only:
  - master

install:
  - npm install
  - npm run build

script:
  - echo "Skipping tests"

env:
  - CLIENT_URL=https://nuxtjs-spotify-marvel.herokuapp.com

deploy:
  provider: heroku
  api_key:
    secure: 7149cd12-03a9-4e23-abbb-b34ef5e10290
  app: nuxtjs-spotify-marvel